using System.Collections.Generic;
using UnityEngine;

public class GridGenerator : MonoBehaviour
{
    [Header("Grid")]
    public Grid grid;

    [Header("Prefabs")]
    public GameObject prefabTierraCultivo;
    public GameObject[] prefabsObstaculos;

    [Header("Tamaño")]
    [Range(1, 20)] public int filas = 5;
    [Range(1, 20)] public int columnas = 5;

    [Header("Obstáculos")]
    [Range(0, 1)] public float probabilidadObstaculo = 0.1f;

    private GameObject[,] celdas;
    private readonly Dictionary<Vector2Int, GameObject> cropVisuals = new Dictionary<Vector2Int, GameObject>();
    [Tooltip("Child containing only crop visuals in the crop tile prefab.")]
    [SerializeField] private string cropChildPath = "Maiz";
    private GameObject generatedRoot;
    [Tooltip("Turn off when the field is generated by SimulationViewController.")]
    public bool generateOnStart = true;

    private void Start()
    {
        if (generateOnStart)
            GenerarParcela(filas, columnas);
    }

    public void GenerarParcela(int nuevasFilas, int nuevasColumnas)
    {
        if (!ValidateSetup(nuevasFilas, nuevasColumnas)) return;
        ClearGeneratedGrid();
        CreateRoot();
        filas = nuevasFilas;
        columnas = nuevasColumnas;
        celdas = new GameObject[filas, columnas];

        for (int f = 0; f < filas; f++)
        {
            for (int c = 0; c < columnas; c++)
            {

                Vector3Int celdaGrid = new Vector3Int(c, 0, f);

                Vector3 posicionMundo = grid.GetCellCenterWorld(celdaGrid);

                GameObject prefabAUsar = DecidirPrefab();

                GameObject instancia = Instantiate(prefabAUsar, posicionMundo, Quaternion.identity, generatedRoot.transform);
                celdas[f, c] = instancia;
            }
        }

        Debug.Log($"Parcela generada: {filas}x{columnas}, {celdas.Length} celdas instanciadas.");
    }

    private GameObject DecidirPrefab()
    {
        if (Random.value < probabilidadObstaculo && prefabsObstaculos != null && prefabsObstaculos.Length > 0)
        {
            int index = Random.Range(0, prefabsObstaculos.Length);
            return prefabsObstaculos[index] != null ? prefabsObstaculos[index] : prefabTierraCultivo;
        }
        return prefabTierraCultivo;
    }

    // Python coordinates are world-grid coordinates. Keep the field offset intact.
    public bool GenerateFromSimulation(WebSocketController.SimulationMessage message)
    {
        var field = message?.world?.field;
        if (field == null || !ValidateSetup(field.height, field.width)) return false;
        if (field.x < 0 || field.y < 0 ||
            (long)field.x + field.width > message.world.width ||
            (long)field.y + field.height > message.world.height)
        {
            Debug.LogError("Python field lies outside its world bounds.", this);
            return false;
        }

        var obstacles = new HashSet<Vector2Int>();
        foreach (var cell in message.obstacles ?? System.Array.Empty<WebSocketController.CellPosition>())
        {
            if (cell == null || cell.x < field.x || cell.y < field.y ||
                cell.x >= field.x + field.width || cell.y >= field.y + field.height)
            {
                Debug.LogError("Python obstacle lies outside the field.", this);
                return false;
            }
            obstacles.Add(new Vector2Int(cell.x, cell.y));
        }

        var obstaclePrefabs = new List<GameObject>();
        foreach (var prefab in prefabsObstaculos ?? System.Array.Empty<GameObject>())
            if (prefab != null) obstaclePrefabs.Add(prefab);
        if (obstacles.Count > 0 && obstaclePrefabs.Count == 0)
        {
            Debug.LogError("Assign at least one obstacle tile prefab to GridGenerator.", this);
            return false;
        }

        ClearGeneratedGrid();
        CreateRoot();
        filas = field.height;
        columnas = field.width;
        celdas = new GameObject[filas, columnas];
        int obstacleIndex = 0;
        bool warnedMissingCrop = false;
        for (int row = 0; row < filas; row++)
        for (int column = 0; column < columnas; column++)
        {
            int x = field.x + column;
            int y = field.y + row;
            bool isObstacle = obstacles.Contains(new Vector2Int(x, y));
            // Obstacle locations come exclusively from Python; cycle visual variants.
            GameObject prefab = isObstacle
                ? obstaclePrefabs[obstacleIndex++ % obstaclePrefabs.Count]
                : prefabTierraCultivo;
            GameObject instance = Instantiate(prefab, CellToWorld(x, y), Quaternion.identity, generatedRoot.transform);
            instance.name = $"Cell_{x}_{y}_{(isObstacle ? "Obstacle" : "Crop")}";
            celdas[row, column] = instance;
            if (!isObstacle)
            {
                Transform crop = instance.transform.Find(cropChildPath);
                if (crop != null)
                    cropVisuals.Add(new Vector2Int(x, y), crop.gameObject);
                else if (!warnedMissingCrop)
                {
                    Debug.LogWarning($"Crop prefab has no child '{cropChildPath}'. Assign Crop Child Path to enable harvest visuals.", this);
                    warnedMissingCrop = true;
                }
            }
        }
        Debug.Log($"Python field generated: {columnas}x{filas}, offset ({field.x},{field.y}), {obstacles.Count} obstacles.", this);
        return true;
    }

    public Vector3 CellToWorld(int x, int y) => grid.GetCellCenterWorld(new Vector3Int(x, 0, y));

    public void MarkHarvested(int x, int y)
    {
        var cell = new Vector2Int(x, y);
        if (!cropVisuals.TryGetValue(cell, out GameObject crop)) return;
        if (crop != null) crop.SetActive(false);
        cropVisuals.Remove(cell);
    }

    public Bounds GetFieldBounds(WebSocketController.FieldData field)
    {
        var bounds = new Bounds(CellToWorld(field.x, field.y), Vector3.zero);
        bounds.Encapsulate(CellToWorld(field.x + field.width - 1, field.y));
        bounds.Encapsulate(CellToWorld(field.x, field.y + field.height - 1));
        bounds.Encapsulate(CellToWorld(field.x + field.width - 1, field.y + field.height - 1));
        bounds.Expand(new Vector3(Mathf.Abs(grid.cellSize.x * grid.transform.lossyScale.x), 0,
            Mathf.Abs(grid.cellSize.z * grid.transform.lossyScale.z)));
        if (generatedRoot != null)
        {
            foreach (var renderer in generatedRoot.GetComponentsInChildren<Renderer>())
                bounds.Encapsulate(renderer.bounds);
            foreach (var terrain in generatedRoot.GetComponentsInChildren<Terrain>())
            {
                if (terrain.terrainData == null) continue;
                var local = terrain.terrainData.bounds;
                for (int i = 0; i < 8; i++)
                    bounds.Encapsulate(terrain.transform.TransformPoint(local.center + Vector3.Scale(local.extents,
                        new Vector3((i & 1) == 0 ? -1 : 1, (i & 2) == 0 ? -1 : 1, (i & 4) == 0 ? -1 : 1))));
            }
        }
        return bounds;
    }

    public void ClearGeneratedGrid()
    {
        cropVisuals.Clear();
        if (generatedRoot != null)
        {
            generatedRoot.SetActive(false);
            Destroy(generatedRoot);
        }
        generatedRoot = null;
        celdas = null;
    }

    private void CreateRoot()
    {
        generatedRoot = new GameObject("Generated Field");
        generatedRoot.transform.SetParent(transform, false);
    }

    private bool ValidateSetup(int rows, int columns)
    {
        if (grid == null || prefabTierraCultivo == null || rows <= 0 || columns <= 0 || (long)rows * columns > 100000)
        {
            Debug.LogError("GridGenerator needs a Grid, crop prefab, and valid dimensions (up to 100,000 cells).", this);
            return false;
        }
        return true;
    }
}
